title: Xavie.Xu
author: Xu Zewei
email: xuzewei@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  When you're curious, you find lots of interseting things to do.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
